image: shortishly/docker-erlang

stages:
  - build

app:
  stage: build
  script:
    - make
    - docker login -e $DOCKER_EMAIL -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker tag $(bin/release_name):$(bin/version) $DOCKER_USERNAME/$(bin/app):$(bin/version)
    - docker push $DOCKER_USERNAME/$(bin/app):$(bin/version)
  only:
    - master
